### ISSUE TITLE
Live stream displayed in right end and getting cut off

### ISSUE THREAD

**Issue by KCastiglione** [flavioribeiro/clappr-rtmp-plugin#12]
Live stream displayed in right end and getting cut off

Here is a screenshot:
http://i.imgur.com/gZMd0WO.png

The top one is a live stream using video.js, the bottom one is using clappr - rtmp plugin from here: http://flv.io/rtmp-plugin.html

**Comment by flavioribeiro** [comment]
@KCastiglione thanks for reporting. Can you send me this RTMP source? email _at_ flavioribeiro.com

**Comment by KCastiglione** [comment]
@flavioribeiro sent.

**Comment by tarkanlar** [comment]
I had the same error. This is not the solution of course but when I made player size 640 x 360  it started to be working properly.

**Comment by flavioribeiro** [comment]
@KCastiglione are we still able to reproduce this problem?

**Comment by flavioribeiro** [comment]
@KCastiglione, @tarkanlar any news on that?
