### ISSUE TITLE
On firefox and IE problem scale video size to player size 

### ISSUE THREAD

**Issue by wicherdt** [flavioribeiro/clappr-rtmp-plugin#15]
When video stream size is more then 640x360 (live encoder)
on player (web page) video stream don't fill player size, video stream is like "overscan" bottom right.
Example:
stream 1280x720
player 854x480
In firefox and IE overscan bottom right.
But in Chrome fill OK?
Problem occur with rtmp plugin (hls OK)

**Comment by chriswiggins** [comment]
See #16

**Comment by chriswiggins** [comment]
I've addressed this in #19 - suggest we close this issue and track it there.
