### ISSUE TITLE
Passing Parameters to RTMP.swf

### ISSUE THREAD

**Issue by pcgeonet** [flavioribeiro/clappr-rtmp-plugin#42]
Hello, 

Flash newbie here.
I am trying to load a the RTMP.swf file in a browser and pass some parameters.
It is posible to play a RTMP video like this?
http://domain.tld/dist/assets/RTMP.swf?source=rtmp://domain.tld/live/livestream&bgcolor=#ff6600

Thank you!

**Comment by gfronza** [comment]
That won't work with the RTMP.swf movie because it doesn't expect a parameter source. The source is actually passed to the playerPlay function, so you would have to have at least a piece of JS to setup the SWF movie and call playerPlay.
