### ISSUE TITLE
Problem switching quality

### ISSUE THREAD

**Issue by uves** [flavioribeiro/clappr-rtmp-plugin#43]
The problem occurs with the switching version , the first time a change is made ,
another has not only changes the label , but the quality is not affected.

I use clappr-rtmp-plugin and clappr-level-selector-plugin.

**Comment by gfronza** [comment]
@uves What version of clappr, clappr-rtmp-plugin and clappr-level-selector are you using? Can you provide us a url of a stream that you see the problem happening?

**Comment by uves** [comment]
Hello, I use latest version:

//cdn.clappr.io/latest/clappr.js
//cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js
//cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js

My setup:
var player = new Clappr.Player({
	source: "http://192.168.0.129/2016/streaming/list.smil",
	parentId: "#player-wrapper",
	plugins: {'playback': [RTMP],'core': [LevelSelector]},
	rtmpConfig: {
		playbackType: 'live',
		autoPlay: true,
		bufferTime: 1,
		startLevel: -1
	}
});

It seems as if it was a problem with the flash . Maybe this will help ?
https://forums.adobe.com/thread/604008?tstart=0

**Comment by gfronza** [comment]
@uves any news on this?

**Comment by gfronza** [comment]
@uves you might want to try the version 0.0.17 (just released). We made a few changes in the way we report levels and level changes. We found a bug related to the "auto switch" featured, it was not updating the label properly.
