### ISSUE TITLE
need help for setup simple pre-roll ads ,with Clappr video player

### ISSUE THREAD

**Issue by sportexholdings** [flavioribeiro/clappr-rtmp-plugin#50]
Hi!, I am trying to setup simple pre-roll video or vast feed pre roll before the video start using clappr video player.i have tried,many times..but any of attempts not succeed.so,i am looking help from you.
Kindly regards!,
Sam

some thing similar to this:
```
<script>
Clappr('example_video_1', {}, function(){ 
  var player = this;
  player.preroll({
    src:"advertisement.mp4"
  });
});
</script>

```
sample link:  https://github.com/dirkjanm/videojs-preroll

**Comment by flavioribeiro** [comment]
hey @sportexholdings this is the repo for the RTMP support on Clappr. For questions related to the player itself, you should go to https://github.com/clappr/clappr/issues.
