### ISSUE TITLE
RTMP logging error

### ISSUE THREAD

**Issue by sarat1669** [flavioribeiro/clappr-rtmp-plugin#53]
Clapper player : 0.2.58
rtmp version : 0.13

log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
log.js:67[error][t] error on event o13:progress trigger - TypeError: this.el.getBytesLoaded is not a function(…)
...

The video is playing fine but i keep getting these logs

**Comment by sarat1669** [comment]
That is a live stream and the progress bar is at 100%. Here is the code that i am using. I removed the rtmp stream intentionally.
`var player= []`
`	var changeVideo = function(videoURL, parentId){ `
`		if(player[parentId]!=undefined) player[parentId].destroy();`
`		player[parentId] = new Clappr.Player({`
`		    source: videoURL,`
`		    parentId: '#'+parentId,`
`		    plugins: {'playback': [RTMP]},`
`		    rtmpConfig: {`
`		        swfPath: 'RTMP.swf',`
`		        scaling:'stretch',`
`		        playbackType: 'live',
`		        bufferTime: 1,`
`		        startLevel: 0,`
`		    },`
`		    autoPlay: true`
`		});`
`		player[parentId].play()`
`		player[parentId].listenTo(`
`			player[parentId].core.getCurrentContainer(),`
`			Clappr.Events.FRAG_LOADED,`
`			function(e,s) {`
`				console.log(e);`
`				console.log(s)`
`			}`
`		)`
`		return player[parentId]`
`	}`
`	changeVideo("rtmp://XXXXXXXXXXXXXXXXXXXXXXXXX", "player")`

**Comment by gfronza** [comment]
That's weird, because the getBytesLoaded exists: https://github.com/flavioribeiro/clappr-rtmp-plugin/blob/master/src/RTMP.as#L128

Is there any chance you have the RTMP.swf cached in your browser (the previous version of RTMP.swf didn't have that function).

**Comment by sarat1669** [comment]
This is the only version that i have used. I think getBytesTotal is not valid for live streams. I made the following changes that fixed this error. I chose 100 so that the progress bar is always to the right end.

 ```
        if(this._playbackType === _playback2.default.LIVE){
 	      	this.trigger(_events2.default.PLAYBACK_PROGRESS, {
 		      start: 0,
 		      current: 100,
 		      total: 100
 		    });
 	      } else {
 	      	this.trigger(_events2.default.PLAYBACK_PROGRESS, {
 		      start: 0,
 		      current: this.el.getBytesLoaded(),
 		      total: this.el.getBytesTotal()
 		    });
 	      }
```

**Comment by gfronza** [comment]
@sarat1669 I tested here, calling el.getBytesLoaded in a live stream it returns 0. To go any further we'll need a link of your "app" where this problem can be reproduced.

**Comment by ocramot** [comment]
Same as https://github.com/flavioribeiro/clappr-rtmp-plugin/issues/23

The missing functions (getBytesLoaded and getBytesTotal) were added in 6 July: https://github.com/flavioribeiro/clappr-rtmp-plugin/commit/e4d053bd0f798a0eb05f232048e1e09889ae672d

However the url http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js is still pointing to an old version of the plugin. So either you have to build the plugin yourself, or wait for someone to build and update the latest version.
