### ISSUE TITLE
OnClick event not firing when using rtmp plugin 

### ISSUE THREAD

**Issue by sarat1669** [flavioribeiro/clappr-rtmp-plugin#54]
Clappr version : 0.2.58
RTMP version : 0.13
The click event works for HLS, normal video playbacks, but when using RTMP, it is not firing.
```
player.listenTo(
	player[parentId].core.getCurrentContainer(),
	Clappr.Events.CONTAINER_CLICK,
	function(ev, data) {
		console.log('clicked on '+ parentId);
	}
)
```

**Comment by gfronza** [comment]
@sarat1669 this probably doesn't work because of the heavyweight flash object, the click event never reaches the Clappr container. I guess we could find a workaround, but not sure if it worth it.
