### ISSUE TITLE
Plugin is not working with any clappr release

### ISSUE THREAD

**Issue by sarat1669** [flavioribeiro/clappr-rtmp-plugin#67]
I was using release 13 which was compatible with clappr 2.58.
It stopped working from one day.
I tried with the latest version also its not working. 
Here is the code
```

<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<div id="player"></div>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
		<script type="text/javascript" src="rtmp.min.js"></script>
		<script>
			var player = new Clappr.Player({
				source: "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov",
				parentId: "#player",
	            autoPlay: true,
	            plugins: {'playback': [RTMP]},
	            rtmpConfig: {
	                swfPath: 'assets/RTMP.swf',
	                scaling:'stretch',
	                playbackType: 'live',
	                bufferTime: 1,
	                startLevel: 0,
	            }
            })
		</script>
	</body>
</html>
```

**Comment by ThalysonR** [comment]
Check your browsers, opera and chromium don't support flash anymore

**Comment by sarat1669** [comment]
@ThalysonR but i'm using chrome, JWPlayer works fine with RTMP. It also uses flash right?
Now the player started working, it was down for 2 days last week, I don't remember the date but please check if there is any date related bug. For that two days I had to fallback to JWPlayer.

**Comment by flavioribeiro** [comment]
hey @sarat1669 since there's no modification here on the plugin neither new releases on clappr (https://github.com/clappr/clappr/releases) I'm wondering if it was something on your side. Any thoughts on that @leandromoreira ?

**Comment by flavioribeiro** [comment]
I'm closing this one, btw
